version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: luka23012005
      MYSQL_DATABASE: luka_pis
      MYSQL_USER: luka_pis
      MYSQL_PASSWORD: luka23012005
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      #Hello